events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        # The port inside the container
        listen 443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;

        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;
        
        # Where the files are served from
        root /var/www/html;
        index index.php;

        server_name www.hkasamat.42.fr hkasamat.42.fr;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            try_files $uri =404;
            # "my-wordpress" is the service name we will define in docker-compose
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            
            # These parameters tell PHP-FPM exactly which file to execute
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}